trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: replacetokens@3
  inputs:
    targetFiles: 'mycloud/__init__.py'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- task: GitVersion@5

- script: |
    python setup.py install
  displayName: 'Install myCloud CLI'

- script: |
    python -m pytest
  displayName: 'Run tests'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'thomasgassmann/mycloud-cli'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(GitVersion.MajorMinorPatch)
      latest
