MY_CLOUD_BIG_FILE_CHUNK_SIZE = 5120000
ENCRYPTION_CHUNK_LENGTH = 1024
MY_CLOUD_MAX_FILE_SIZE = 10240000
BASE_DIR = '/Drive/'
AES_EXTENSION = '.aes'
PARTIAL_EXTENSION = '.partial'
START_NUMBER_LENGTH = 8